name: Push Tagged Release to Production Repo

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger only on tags like v1.0.0, v2.3.1, etc.

jobs:
  push-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev repo
        uses: actions/checkout@v3

      - name: Push tag and commit to Production repo
        env:
          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          git config --global user.name "elliott-fogg"
          git config --global user.email "elliott-fogg@users.noreply.github.com"

          # Add Production repo as remote with token authentication
          git remote add prod "https://x-access-token:${PROD_REPO_TOKEN}@github.com/elliott-fogg/pwa-website-prod.git"

          # Push the tag to Production repo
          git push prod refs/tags/${TAG_NAME} --force

          # Also push the tagged commit to main branch in Production repo (force update)
          git push prod ${TAG_NAME}:main --force
